// tools/publish/lib/templates/coc/skills-data.js
// Base values are the standard CoC 7e starting percentages (game math, BRP ORC).
const REGENCY_SKILLS = [
  { name: 'Accounting', base: 5 }, { name: 'Animal Handling', base: 5 },
  { name: 'Anthropology', base: 1 }, { name: 'Appraise', base: 5 },
  { name: 'Archaeology', base: 1 }, { name: 'Art/Craft', base: 5 },
  { name: 'Artillery', base: 1 }, { name: 'Astronomy', base: 1 },
  { name: 'Charm', base: 15 }, { name: 'Climb', base: 20 },
  { name: 'Credit Rating', base: 0 }, { name: 'Cthulhu Mythos', base: 0 },
  { name: 'Dancing', base: 5 }, { name: 'Demolitions', base: 1 },
  { name: 'Disguise', base: 5 }, { name: 'Dodge', base: 0 },
  { name: 'Drive Carriage', base: 20 }, { name: 'Etiquette', base: 5 },
  { name: 'Fashion', base: 10 }, { name: 'Fast Talk', base: 5 },
  { name: 'Fighting (Brawl)', base: 25 }, { name: 'Firearms (Pistol)', base: 20 },
  { name: 'Firearms (Rifle/Blunderbuss)', base: 25 }, { name: 'First Aid', base: 30 },
  { name: 'Gaming', base: 10 }, { name: 'History', base: 5 },
  { name: 'Intimidate', base: 15 }, { name: 'Jump', base: 20 },
  { name: 'Language (Own)', base: 0 }, { name: 'Language (Other)', base: 1 },
  { name: 'Law', base: 5 }, { name: 'Library Use', base: 20 },
  { name: 'Listen', base: 20 }, { name: 'Locksmith', base: 1 },
  { name: 'Lore', base: 1 }, { name: 'Mechanical Repair', base: 10 },
  { name: 'Medicine', base: 1 }, { name: 'Mesmerism', base: 1 },
  { name: 'Natural Philosophy', base: 1 }, { name: 'Natural World', base: 10 },
  { name: 'Navigate', base: 10 }, { name: 'Occult', base: 5 },
  { name: 'Persuade', base: 10 }, { name: 'Pilot (Boat)', base: 1 },
  { name: 'Psychology', base: 10 }, { name: 'Read Lips', base: 1 },
  { name: 'Reassure', base: 5 }, { name: 'Religion', base: 10 },
  { name: 'Ride', base: 5 }, { name: 'Sleight of Hand', base: 10 },
  { name: 'Spot Hidden', base: 25 }, { name: 'Stealth', base: 20 },
  { name: 'Survival', base: 10 }, { name: 'Swim', base: 20 },
  { name: 'Throw', base: 20 }, { name: 'Track', base: 10 },
];
// Base CoC 7e differs: Drive Auto (not Carriage), no Reputation-linked skills,
// Credit Rating carries wealth, Science/Hypnosis instead of Natural Philosophy/Mesmerism.
const BASE_SKILLS = [
  { name: 'Accounting', base: 5 }, { name: 'Anthropology', base: 1 },
  { name: 'Appraise', base: 5 }, { name: 'Archaeology', base: 1 },
  { name: 'Art/Craft', base: 5 }, { name: 'Charm', base: 15 },
  { name: 'Climb', base: 20 }, { name: 'Credit Rating', base: 0 },
  { name: 'Cthulhu Mythos', base: 0 }, { name: 'Disguise', base: 5 },
  { name: 'Dodge', base: 0 }, { name: 'Drive Auto', base: 20 },
  { name: 'Electrical Repair', base: 10 }, { name: 'Fast Talk', base: 5 },
  { name: 'Fighting (Brawl)', base: 25 }, { name: 'Firearms (Handgun)', base: 20 },
  { name: 'Firearms (Rifle/Shotgun)', base: 25 }, { name: 'First Aid', base: 30 },
  { name: 'History', base: 5 }, { name: 'Intimidate', base: 15 },
  { name: 'Jump', base: 20 }, { name: 'Language (Own)', base: 0 },
  { name: 'Language (Other)', base: 1 }, { name: 'Law', base: 5 },
  { name: 'Library Use', base: 20 }, { name: 'Listen', base: 20 },
  { name: 'Locksmith', base: 1 }, { name: 'Mechanical Repair', base: 10 },
  { name: 'Medicine', base: 1 }, { name: 'Natural World', base: 10 },
  { name: 'Navigate', base: 10 }, { name: 'Occult', base: 5 },
  { name: 'Operate Heavy Machinery', base: 1 }, { name: 'Persuade', base: 10 },
  { name: 'Pilot', base: 1 }, { name: 'Psychoanalysis', base: 1 },
  { name: 'Psychology', base: 10 }, { name: 'Ride', base: 5 },
  { name: 'Science', base: 1 }, { name: 'Sleight of Hand', base: 10 },
  { name: 'Spot Hidden', base: 25 }, { name: 'Stealth', base: 20 },
  { name: 'Survival', base: 10 }, { name: 'Swim', base: 20 },
  { name: 'Throw', base: 20 }, { name: 'Track', base: 10 },
];
module.exports = { REGENCY_SKILLS, BASE_SKILLS };
